#!/bin/bash

LDFLAGS="-lglfw -lGL -lGLEW -lm"
SRCDIR=src

objects_string=""
for i in $(ls $SRCDIR/*.c -1 | sed -e 's/\.c$//');
do
	gcc -c $i".c" -o $i".o" -std=c11 -g
	objects_string="$objects_string "$i".o "
done;

gcc -o b1 $objects_string $LDFLAGS

rm $SRCDIR/*.o